steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'helloworld', '--image=gcr.io/$PROJECT_ID/helloworld',
      '--set-env-vars', 'DB_USER=$_DB_USER,DB_PASS=$_DB_PASS,INSTANCE_CONNECTION_NAME=$_INSTANCE_CONNECTION_NAME,DB_NAME=$_DB_NAME',
      '--add-cloudsql-instances=$_INSTANCE_NAME', '--platform=managed',
      '--region=asia-northeast1'
    ]
images: ['gcr.io/$PROJECT_ID/helloworld']
