version: '3.7'
services:
  app:
    build: .
    command: ['/entrypoint.sh']
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
      DB_NAME: ${DB_NAME}
    volumes:
      - dbsocket:/cloudsql
      - ./dev/entrypoint.sh:/entrypoint.sh
    ports:
      - 8765:8080
    depends_on:
      - socket
  socket:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command:
      [
        '/cloud_sql_proxy',
        '-dir=/cloudsql',
        '-instances=${INSTANCE_CONNECTION_NAME}',
        '-credential_file=/config/iwara-collector.json',
      ]
    volumes:
      - ./keys/iwara-collector-888af0a072ee.json:/config/iwara-collector.json
      - dbsocket:/cloudsql
volumes:
  dbsocket:
